name: Build PCAPdroid APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build APK (debug)
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: PCAPdroid-debug
          path: app/build/outputs/apk/debug/

      # - name: Build APK (release)
      #   # Внимание: Для сборки релизной версии вам понадобятся:
      #   # 1. Создать keystore файл и добавить его в секреты GitHub.
      #   # 2. Добавить переменные окружения для keystore паролей и alias в секреты GitHub.
      #   #
      #   # run: ./gradlew assembleRelease
      #   run: echo "Release build is skipped. Uncomment and configure for release builds."

      # - name: Upload release APK
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: PCAPdroid-release
      #     path: app/build/outputs/apk/release/
