name: Debug build

on: [push, pull_request]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/playstore'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - run: ./gradlew test
    - run: ./gradlew assembleDebug -PdoNotStrip
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
